Explore main page for mobile
spectatorpublishing/Clubs-2020 pull request #104
Opened 2020-12-04 19:01 UTC by fcavuoti

2020-12-11 19:08 UTC, erin2722 requested changes
Two small codebase-style changes, but otherwise this looks incredible!!!

Also, when you repush can you pull from frontend first to resolve the conflicts?

This is awesome, and thank you! 👍 🎉

2020-12-11 19:08 UTC, erin2722 commented on client/src/components/filters/filterMobile.js
> +const blue = '#42B7CB';
for the colors here, could we use theme provider?

2020-12-11 19:08 UTC, erin2722 commented on client/src/components/filters/filterMobile.js
> +export default class FilterMobile extends React.Component {
can we switch this to hooks instead of class components?

2021-02-05 19:05 UTC, lauracastrovenegas requested changes
Looks great!! 👏🏻👏🏻 Great job with the state. Looks very clean 😁 It is ready to go and merge after just one small change.

I know it's a little irrelevant to what you were doing but could you go through the styling for the explore page and the shuffle.js and change the hardcoded color values to use props:` ${(props) => props.theme.colors.white};`? I pointed out a few spots on the explore page but there are a few in the shuffle.js file as well. Just a quick fix that we can include in our merge, killing two birds with one stone.

Otherwise, looks amazing!! Once you push those styling prop changes I will merge!

2021-02-05 23:15 UTC, lauracastrovenegas approved these changes
WOW! So great that you were able to convert those components to hooks! Really great job!! 😁🎉

2021-02-05 23:21 UTC, merged